#!/usr/bin/env bash

EDGEFUSION_SERVICE_NAME="${EDGEFUSION_SERVICE_NAME:-edgefusion}"
EDGEFUSION_USER="${EDGEFUSION_USER:-$EDGEFUSION_SERVICE_NAME}"
EDGEFUSION_CONFIG_DIR="${EDGEFUSION_CONFIG_DIR:-/etc/$EDGEFUSION_SERVICE_NAME}"
EDGEFUSION_DATA_DIR="${EDGEFUSION_DATA_DIR:-/var/lib/$EDGEFUSION_SERVICE_NAME}"
EDGEFUSION_LOG_DIR="${EDGEFUSION_LOG_DIR:-/var/log/$EDGEFUSION_SERVICE_NAME}"
EDGEFUSION_CONFIG_FILE="${EDGEFUSION_CONFIG_FILE:-$EDGEFUSION_CONFIG_DIR/config.yaml}"
EDGEFUSION_DB_PATH="${EDGEFUSION_DB_PATH:-$EDGEFUSION_DATA_DIR/edgefusion.db}"
EDGEFUSION_DB_URL="${EDGEFUSION_DB_URL:-sqlite:///$EDGEFUSION_DB_PATH}"

export EDGEFUSION_SERVICE_NAME
export EDGEFUSION_USER
export EDGEFUSION_CONFIG_DIR
export EDGEFUSION_DATA_DIR
export EDGEFUSION_LOG_DIR
export EDGEFUSION_CONFIG_FILE
export EDGEFUSION_DB_PATH
export EDGEFUSION_DB_URL
